Option Strict On
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports Microsoft.VisualBasic.ApplicationServices
Imports System.IO
Namespace My

     'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
     ' or if you encounter build errors in this file, go to the Project Designer
     ' (go to Project Properties or double-click the My Project node in
     ' Solution Explorer), and make changes on the Application tab.
     '
     Partial Friend Class MyApplication

          <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
          Public Sub New()
               MyBase.New(Global.Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows)
               Me.IsSingleInstance = False
               Me.EnableVisualStyles = True
               Me.SaveMySettingsOnExit = True
               Me.ShutdownStyle = Global.Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
          End Sub

          <Global.System.Diagnostics.DebuggerStepThroughAttribute()>
          Protected Overrides Sub OnCreateMainForm()
               Me.MainForm = Global.Otalio.Import.frmMainMenu
          End Sub

          Private Sub MyApplication_UnhandledException(sender As Object, e As UnhandledExceptionEventArgs) Handles Me.UnhandledException
               Dim sPath As String = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)

               If Directory.Exists(Path.Combine(sPath, "Otalio Import")) = False Then
                    Directory.CreateDirectory(Path.Combine(sPath, "Otalio Import"))
               End If

               Dim myFilePath As String = sPath & "\Otalio Import\" & String.Format("GT Error Log {0} {1} {2}.txt", Today.Year.ToString, Today.Month.ToString, Today.Day.ToString)

               Using sw As New StreamWriter(File.Open(myFilePath, FileMode.Append))
                    sw.WriteLine(DateTime.Now)
                    sw.WriteLine(e.Exception.ToString)
                    sw.WriteLine(vbNewLine)
                    sw.WriteLine(vbNewLine)
               End Using

               Resume Next

          End Sub
     End Class
End Namespace
